
#FIXME 
obj-$(CONFIG_VCP) += hw_config.o
obj-$(CONFIG_VCP) += stm32_it.o
obj-$(CONFIG_VCP) += usb_desc.o
obj-$(CONFIG_VCP) += usb_endp.o
obj-$(CONFIG_VCP) += usb_istr.o
obj-$(CONFIG_VCP) += usb_prop.o
obj-$(CONFIG_VCP) += usb_pwr.o
