obj-$(CONFIG_BEEPER) += beeper.o
obj-$(CONFIG_TRANSPONDER) += transponder_ir.o
obj-$(CONFIG_GIMBAL)	+= gimbal.o
obj-$(CONFIG_GPS)	+= gps.o
obj-$(CONFIG_LED_STRIP)	+= ledstrip.o
obj-$(CONFIG_SERIAL_4WAY_BLHELI_INTERFACE) += serial_4way_avrootloader.o \
			serial_4way.o serial_4way_stk500v2.o
obj-$(CONFIG_DISPLAY)	+= display.o
obj-y += flashfs.o
obj-y += motor_and_servo.o
obj-y += serial.o
obj-y += serial_cli.o
obj-y += statusindicator.o
