#
# Makefile for the Telemetry subsystem.
#

obj-$(CONFIG_TELEMETRY_FRSKY) += frsky.o
obj-$(CONFIG_TELEMETRY_HOTT) += hott.o
obj-$(CONFIG_TELEMETRY_LTM) += ltm.o
obj-$(CONFIG_TELEMETRY_MAVLINK) += mavlink.o
obj-$(CONFIG_TELEMETRY_SMARTPORT) += smartport.o
obj-$(CONFIG_TELEMETRY) += telemetry.o
