obj-$(CONFIG_OSD) += osd_tasks.o
obj-$(CONFIG_OSD) += osd_serial.o
obj-$(CONFIG_OSD) += osd_screen.o

# FIXME
ifdef CONFIG_VIDEO_MAX7456
obj-$(CONFIG_OSD) += osd_max7456.o
obj-$(CONFIG_OSD) += fonts/font_max7456_12x18.o
endif

obj-$(CONFIG_OSD) += osd_element_render.o
obj-$(CONFIG_OSD) += osd_element.o
obj-$(CONFIG_OSD) += osd.o
obj-$(CONFIG_OSD) += msp_server_osd.o
obj-$(CONFIG_OSD) += msp_client_osd.o
obj-$(CONFIG_OSD) += fc_state.o
obj-$(CONFIG_OSD) += config.o
obj-$(CONFIG_OSD) += cleanflight_osd.o
obj-$(CONFIG_OSD) += boot.o
